services:
  database: 
    container_name: pgdatabase
    image: postgres:16.4-alpine
    command: postgres
    restart: always
    ports: 
      - "5438:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: videocal
      POSTGRES_DB: todos-db
      POSTGRES_PASSWORD: root
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: dich140804@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports: 
      - 5050:80