services:
  database: 
    container_name: pgdatabase
    restart: always
    image: postgres:16.4-alpine
    command: postgres
    ports: 
      - "5438:5432"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER_NAME}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes: 
      - postgres_data:/vol/lib/postgresql/data
    networks: 
      - backend
    
  pgadmin:
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports: 
      - 5050:80
    networks: 
      - backend

  redis: 
    container_name: redis
    image: redis:5.0
    restart: always
    ports: 
      - "5448:5442"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis_data:/data
    networks: 
      - backend

volumes: 
  postgres_data:
  redis_data:

networks: 
  backend: